name: Format

on:
  pull_request:
    branches: [ "main" ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Check Last Commit
        id: check_commit
        run: |
          last_commit_message=$(git log -1 --pretty=format:%s)
          if [[ $last_commit_message == *"style: formatted by github action"* ]]; then
            echo "Commit message matches. Skipping workflow."
            exit 0
          else
            echo "Commit message doesn't match. Continuing workflow."
            exit 1
          fi

      - name: Prettify code
        if: steps.check_commit.outcome == 'failure'
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.md
          only_changed: True
          commit_message: "style: formatted by github action"
