name: Format

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Last Commit Message
        id: get_commit_message
        run: |
          last_commit_message=$(git log -1 --pretty=format:%s)
          echo "::set-output name=commit_message::$last_commit_message"

      - name: Check Commit Source
        id: check_commit_source
        run: |
          if [[ "${{ steps.get_commit_message.outputs.commit_message }}" == "style: formatted by github action" ]]; then
            echo "Commit message created by workflow. Running Prettier."
            echo "::set-output name=run_prettier::true"
          else
            echo "Commit message created by user. Running Prettier."
            echo "::set-output name=run_prettier::true"
          fi

      - name: Prettify code
        if: steps.check_commit_source.outputs.run_prettier == 'true'
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.md
          only_changed: true
          commit_message: "style: formatted by github action"
